// flow-typed signature: 648c7d862af3abf1d42d1af68cf6476b
// flow-typed version: <<STUB>>/@neutrinojs/karma_v^8.3.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@neutrinojs/karma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@neutrinojs/karma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@neutrinojs/karma/index' {
  declare module.exports: $Exports<'@neutrinojs/karma'>;
}
declare module '@neutrinojs/karma/index.js' {
  declare module.exports: $Exports<'@neutrinojs/karma'>;
}
