// flow-typed signature: 60a5adfd8153ed6c7de34eb3f24da8ea
// flow-typed version: <<STUB>>/babel-preset-lingui-react_v^1.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-lingui-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-lingui-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-lingui-react/index' {
  declare module.exports: $Exports<'babel-preset-lingui-react'>;
}
declare module 'babel-preset-lingui-react/index.js' {
  declare module.exports: $Exports<'babel-preset-lingui-react'>;
}
