// flow-typed signature: 5550fee5fdec535ce78d0f6bd69717c6
// flow-typed version: <<STUB>>/chai-shallow-deep-equal_v^1.4.6/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-shallow-deep-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-shallow-deep-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-shallow-deep-equal/chai-shallow-deep-equal' {
  declare module.exports: any;
}

declare module 'chai-shallow-deep-equal/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-shallow-deep-equal/chai-shallow-deep-equal.js' {
  declare module.exports: $Exports<'chai-shallow-deep-equal/chai-shallow-deep-equal'>;
}
declare module 'chai-shallow-deep-equal/test/test.js' {
  declare module.exports: $Exports<'chai-shallow-deep-equal/test/test'>;
}
