// flow-typed signature: dd3d553ecb0331c231bc33a68fb97da0
// flow-typed version: <<STUB>>/karma-mocha-reporter_v^2.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-mocha-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-mocha-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-mocha-reporter/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-mocha-reporter/index' {
  declare module.exports: $Exports<'karma-mocha-reporter'>;
}
declare module 'karma-mocha-reporter/index.js' {
  declare module.exports: $Exports<'karma-mocha-reporter'>;
}
declare module 'karma-mocha-reporter/symbols.js' {
  declare module.exports: $Exports<'karma-mocha-reporter/symbols'>;
}
