// flow-typed signature: 0c58b9c60a17c9b95c5d91436618ce67
// flow-typed version: <<STUB>>/karma-webpack-with-fast-source-maps_v^1.9.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webpack-with-fast-source-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webpack-with-fast-source-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webpack-with-fast-source-maps/mocha-env-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webpack-with-fast-source-maps/index' {
  declare module.exports: $Exports<'karma-webpack-with-fast-source-maps'>;
}
declare module 'karma-webpack-with-fast-source-maps/index.js' {
  declare module.exports: $Exports<'karma-webpack-with-fast-source-maps'>;
}
declare module 'karma-webpack-with-fast-source-maps/mocha-env-loader.js' {
  declare module.exports: $Exports<'karma-webpack-with-fast-source-maps/mocha-env-loader'>;
}
