// flow-typed signature: 0bab7d5e44814e6e0497cda566901440
// flow-typed version: <<STUB>>/lingui-cli_v^1.3.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lingui-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lingui-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lingui-cli/dist/api/compile' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/extract' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/extractors/babel' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/extractors/index' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/extractors/types' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/extractors/typescript' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/formats/lingui' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/formats/minimal' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/formats/types' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/formats/utils/locales' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/api/stats' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/lingui-add-locale' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/lingui-compile' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/lingui-extract' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/lingui' {
  declare module.exports: any;
}

declare module 'lingui-cli/dist/mocks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lingui-cli/dist/api/compile.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/compile'>;
}
declare module 'lingui-cli/dist/api/extract.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/extract'>;
}
declare module 'lingui-cli/dist/api/extractors/babel.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/extractors/babel'>;
}
declare module 'lingui-cli/dist/api/extractors/index.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/extractors/index'>;
}
declare module 'lingui-cli/dist/api/extractors/types.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/extractors/types'>;
}
declare module 'lingui-cli/dist/api/extractors/typescript.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/extractors/typescript'>;
}
declare module 'lingui-cli/dist/api/formats/lingui.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/formats/lingui'>;
}
declare module 'lingui-cli/dist/api/formats/minimal.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/formats/minimal'>;
}
declare module 'lingui-cli/dist/api/formats/types.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/formats/types'>;
}
declare module 'lingui-cli/dist/api/formats/utils/locales.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/formats/utils/locales'>;
}
declare module 'lingui-cli/dist/api/stats.js' {
  declare module.exports: $Exports<'lingui-cli/dist/api/stats'>;
}
declare module 'lingui-cli/dist/lingui-add-locale.js' {
  declare module.exports: $Exports<'lingui-cli/dist/lingui-add-locale'>;
}
declare module 'lingui-cli/dist/lingui-compile.js' {
  declare module.exports: $Exports<'lingui-cli/dist/lingui-compile'>;
}
declare module 'lingui-cli/dist/lingui-extract.js' {
  declare module.exports: $Exports<'lingui-cli/dist/lingui-extract'>;
}
declare module 'lingui-cli/dist/lingui.js' {
  declare module.exports: $Exports<'lingui-cli/dist/lingui'>;
}
declare module 'lingui-cli/dist/mocks.js' {
  declare module.exports: $Exports<'lingui-cli/dist/mocks'>;
}
