// flow-typed signature: 2be3e39402998b4ea3fdfa24b174c670
// flow-typed version: <<STUB>>/loadable-components_v^0.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loadable-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loadable-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loadable-components/__fixtures__/Book' {
  declare module.exports: any;
}

declare module 'loadable-components/__fixtures__/Books' {
  declare module.exports: any;
}

declare module 'loadable-components/__fixtures__/Dummy' {
  declare module.exports: any;
}

declare module 'loadable-components/__fixtures__/Routes' {
  declare module.exports: any;
}

declare module 'loadable-components/componentTracker' {
  declare module.exports: any;
}

declare module 'loadable-components/componentTracker.test' {
  declare module.exports: any;
}

declare module 'loadable-components/constants' {
  declare module.exports: any;
}

declare module 'loadable-components/loadable' {
  declare module.exports: any;
}

declare module 'loadable-components/loadable.test' {
  declare module.exports: any;
}

declare module 'loadable-components/loadComponents' {
  declare module.exports: any;
}

declare module 'loadable-components/loadComponents.test' {
  declare module.exports: any;
}

declare module 'loadable-components/server/DeferredState' {
  declare module.exports: any;
}

declare module 'loadable-components/server/DeferredState.test' {
  declare module.exports: any;
}

declare module 'loadable-components/server/index' {
  declare module.exports: any;
}

declare module 'loadable-components/server/index.test' {
  declare module.exports: any;
}

declare module 'loadable-components/setupTests' {
  declare module.exports: any;
}

declare module 'loadable-components/snap/index' {
  declare module.exports: any;
}

declare module 'loadable-components/snap/index.test' {
  declare module.exports: any;
}

declare module 'loadable-components/utils/createSymbol' {
  declare module.exports: any;
}

declare module 'loadable-components/utils/resolveModuleDefault' {
  declare module.exports: any;
}

declare module 'loadable-components/utils/resolveModuleDefault.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loadable-components/__fixtures__/Book.js' {
  declare module.exports: $Exports<'loadable-components/__fixtures__/Book'>;
}
declare module 'loadable-components/__fixtures__/Books.js' {
  declare module.exports: $Exports<'loadable-components/__fixtures__/Books'>;
}
declare module 'loadable-components/__fixtures__/Dummy.js' {
  declare module.exports: $Exports<'loadable-components/__fixtures__/Dummy'>;
}
declare module 'loadable-components/__fixtures__/Routes.js' {
  declare module.exports: $Exports<'loadable-components/__fixtures__/Routes'>;
}
declare module 'loadable-components/componentTracker.js' {
  declare module.exports: $Exports<'loadable-components/componentTracker'>;
}
declare module 'loadable-components/componentTracker.test.js' {
  declare module.exports: $Exports<'loadable-components/componentTracker.test'>;
}
declare module 'loadable-components/constants.js' {
  declare module.exports: $Exports<'loadable-components/constants'>;
}
declare module 'loadable-components/index' {
  declare module.exports: $Exports<'loadable-components'>;
}
declare module 'loadable-components/index.js' {
  declare module.exports: $Exports<'loadable-components'>;
}
declare module 'loadable-components/loadable.js' {
  declare module.exports: $Exports<'loadable-components/loadable'>;
}
declare module 'loadable-components/loadable.test.js' {
  declare module.exports: $Exports<'loadable-components/loadable.test'>;
}
declare module 'loadable-components/loadComponents.js' {
  declare module.exports: $Exports<'loadable-components/loadComponents'>;
}
declare module 'loadable-components/loadComponents.test.js' {
  declare module.exports: $Exports<'loadable-components/loadComponents.test'>;
}
declare module 'loadable-components/server/DeferredState.js' {
  declare module.exports: $Exports<'loadable-components/server/DeferredState'>;
}
declare module 'loadable-components/server/DeferredState.test.js' {
  declare module.exports: $Exports<'loadable-components/server/DeferredState.test'>;
}
declare module 'loadable-components/server/index.js' {
  declare module.exports: $Exports<'loadable-components/server/index'>;
}
declare module 'loadable-components/server/index.test.js' {
  declare module.exports: $Exports<'loadable-components/server/index.test'>;
}
declare module 'loadable-components/setupTests.js' {
  declare module.exports: $Exports<'loadable-components/setupTests'>;
}
declare module 'loadable-components/snap/index.js' {
  declare module.exports: $Exports<'loadable-components/snap/index'>;
}
declare module 'loadable-components/snap/index.test.js' {
  declare module.exports: $Exports<'loadable-components/snap/index.test'>;
}
declare module 'loadable-components/utils/createSymbol.js' {
  declare module.exports: $Exports<'loadable-components/utils/createSymbol'>;
}
declare module 'loadable-components/utils/resolveModuleDefault.js' {
  declare module.exports: $Exports<'loadable-components/utils/resolveModuleDefault'>;
}
declare module 'loadable-components/utils/resolveModuleDefault.test.js' {
  declare module.exports: $Exports<'loadable-components/utils/resolveModuleDefault.test'>;
}
