// flow-typed signature: e02921b2700359a590453670c3a9e93f
// flow-typed version: <<STUB>>/neutrino-preset-karma_v^5.8.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino-preset-karma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino-preset-karma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'neutrino-preset-karma/index' {
  declare module.exports: $Exports<'neutrino-preset-karma'>;
}
declare module 'neutrino-preset-karma/index.js' {
  declare module.exports: $Exports<'neutrino-preset-karma'>;
}
