// flow-typed signature: 3d3770a1be6c0fe0ceab9e10571d5493
// flow-typed version: <<STUB>>/neutrino-preset-react_v^6.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neutrino-preset-react/test/react_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neutrino-preset-react/index' {
  declare module.exports: $Exports<'neutrino-preset-react'>;
}
declare module 'neutrino-preset-react/index.js' {
  declare module.exports: $Exports<'neutrino-preset-react'>;
}
declare module 'neutrino-preset-react/test/react_test.js' {
  declare module.exports: $Exports<'neutrino-preset-react/test/react_test'>;
}
