// flow-typed signature: 23a697c680b6da680c36505dc20998ae
// flow-typed version: <<STUB>>/react-s-alert_v^1.2.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-s-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-s-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-s-alert/dist/s-alert-parts/s-alert-data-prep' {
  declare module.exports: any;
}

declare module 'react-s-alert/dist/s-alert-parts/s-alert-store' {
  declare module.exports: any;
}

declare module 'react-s-alert/dist/s-alert-parts/s-alert-tools' {
  declare module.exports: any;
}

declare module 'react-s-alert/dist/SAlert' {
  declare module.exports: any;
}

declare module 'react-s-alert/dist/SAlertContent' {
  declare module.exports: any;
}

declare module 'react-s-alert/dist/SAlertContentTmpl' {
  declare module.exports: any;
}

declare module 'react-s-alert/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-s-alert/dist/s-alert-parts/s-alert-data-prep.js' {
  declare module.exports: $Exports<'react-s-alert/dist/s-alert-parts/s-alert-data-prep'>;
}
declare module 'react-s-alert/dist/s-alert-parts/s-alert-store.js' {
  declare module.exports: $Exports<'react-s-alert/dist/s-alert-parts/s-alert-store'>;
}
declare module 'react-s-alert/dist/s-alert-parts/s-alert-tools.js' {
  declare module.exports: $Exports<'react-s-alert/dist/s-alert-parts/s-alert-tools'>;
}
declare module 'react-s-alert/dist/SAlert.js' {
  declare module.exports: $Exports<'react-s-alert/dist/SAlert'>;
}
declare module 'react-s-alert/dist/SAlertContent.js' {
  declare module.exports: $Exports<'react-s-alert/dist/SAlertContent'>;
}
declare module 'react-s-alert/dist/SAlertContentTmpl.js' {
  declare module.exports: $Exports<'react-s-alert/dist/SAlertContentTmpl'>;
}
declare module 'react-s-alert/index' {
  declare module.exports: $Exports<'react-s-alert'>;
}
declare module 'react-s-alert/index.js' {
  declare module.exports: $Exports<'react-s-alert'>;
}
declare module 'react-s-alert/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-s-alert/scripts/mocha_runner'>;
}
