// flow-typed signature: 6f936df8033e925e9d55b5f371665ea4
// flow-typed version: <<STUB>>/sass-loader_v^4.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sass-loader/index' {
  declare module.exports: $Exports<'sass-loader'>;
}
declare module 'sass-loader/index.js' {
  declare module.exports: $Exports<'sass-loader'>;
}
