// flow-typed signature: e1f9c029ff599693ef7f4e1e58a20f2d
// flow-typed version: <<STUB>>/@lingui/babel-preset-react_v^2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lingui/babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lingui/babel-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@lingui/babel-preset-react/index' {
  declare module.exports: $Exports<'@lingui/babel-preset-react'>;
}
declare module '@lingui/babel-preset-react/index.js' {
  declare module.exports: $Exports<'@lingui/babel-preset-react'>;
}
