// flow-typed signature: 01879e1f12171443f7d288a6ce7abedc
// flow-typed version: <<STUB>>/@lingui/cli_v^2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lingui/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lingui/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lingui/cli/api/compile' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/extract' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/extractors/babel' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/extractors/index' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/extractors/types' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/extractors/typescript' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/formats/lingui' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/formats/minimal' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/formats/types' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/formats/utils/locales' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/index' {
  declare module.exports: any;
}

declare module '@lingui/cli/api/stats' {
  declare module.exports: any;
}

declare module '@lingui/cli/lingui-add-locale' {
  declare module.exports: any;
}

declare module '@lingui/cli/lingui-compile' {
  declare module.exports: any;
}

declare module '@lingui/cli/lingui-extract' {
  declare module.exports: any;
}

declare module '@lingui/cli/lingui' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lingui/cli/api/compile.js' {
  declare module.exports: $Exports<'@lingui/cli/api/compile'>;
}
declare module '@lingui/cli/api/extract.js' {
  declare module.exports: $Exports<'@lingui/cli/api/extract'>;
}
declare module '@lingui/cli/api/extractors/babel.js' {
  declare module.exports: $Exports<'@lingui/cli/api/extractors/babel'>;
}
declare module '@lingui/cli/api/extractors/index.js' {
  declare module.exports: $Exports<'@lingui/cli/api/extractors/index'>;
}
declare module '@lingui/cli/api/extractors/types.js' {
  declare module.exports: $Exports<'@lingui/cli/api/extractors/types'>;
}
declare module '@lingui/cli/api/extractors/typescript.js' {
  declare module.exports: $Exports<'@lingui/cli/api/extractors/typescript'>;
}
declare module '@lingui/cli/api/formats/lingui.js' {
  declare module.exports: $Exports<'@lingui/cli/api/formats/lingui'>;
}
declare module '@lingui/cli/api/formats/minimal.js' {
  declare module.exports: $Exports<'@lingui/cli/api/formats/minimal'>;
}
declare module '@lingui/cli/api/formats/types.js' {
  declare module.exports: $Exports<'@lingui/cli/api/formats/types'>;
}
declare module '@lingui/cli/api/formats/utils/locales.js' {
  declare module.exports: $Exports<'@lingui/cli/api/formats/utils/locales'>;
}
declare module '@lingui/cli/api/index.js' {
  declare module.exports: $Exports<'@lingui/cli/api/index'>;
}
declare module '@lingui/cli/api/stats.js' {
  declare module.exports: $Exports<'@lingui/cli/api/stats'>;
}
declare module '@lingui/cli/lingui-add-locale.js' {
  declare module.exports: $Exports<'@lingui/cli/lingui-add-locale'>;
}
declare module '@lingui/cli/lingui-compile.js' {
  declare module.exports: $Exports<'@lingui/cli/lingui-compile'>;
}
declare module '@lingui/cli/lingui-extract.js' {
  declare module.exports: $Exports<'@lingui/cli/lingui-extract'>;
}
declare module '@lingui/cli/lingui.js' {
  declare module.exports: $Exports<'@lingui/cli/lingui'>;
}
