// flow-typed signature: 7c1967e8146ad328e7ddfd8aab64f267
// flow-typed version: <<STUB>>/@lingui/core_v^2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lingui/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lingui/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lingui/core/cjs/core.development' {
  declare module.exports: any;
}

declare module '@lingui/core/cjs/core.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lingui/core/cjs/core.development.js' {
  declare module.exports: $Exports<'@lingui/core/cjs/core.development'>;
}
declare module '@lingui/core/cjs/core.production.min.js' {
  declare module.exports: $Exports<'@lingui/core/cjs/core.production.min'>;
}
declare module '@lingui/core/index' {
  declare module.exports: $Exports<'@lingui/core'>;
}
declare module '@lingui/core/index.js' {
  declare module.exports: $Exports<'@lingui/core'>;
}
