// flow-typed signature: 11a5fa591346e52f1281110f5852b000
// flow-typed version: <<STUB>>/@lingui/react_v^2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lingui/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lingui/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lingui/react/cjs/react.development' {
  declare module.exports: any;
}

declare module '@lingui/react/cjs/react.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lingui/react/cjs/react.development.js' {
  declare module.exports: $Exports<'@lingui/react/cjs/react.development'>;
}
declare module '@lingui/react/cjs/react.production.min.js' {
  declare module.exports: $Exports<'@lingui/react/cjs/react.production.min'>;
}
declare module '@lingui/react/index' {
  declare module.exports: $Exports<'@lingui/react'>;
}
declare module '@lingui/react/index.js' {
  declare module.exports: $Exports<'@lingui/react'>;
}
